# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Machines in Motion Laboratory
email: ludovic.righetti@nyu.edu
first_name: Ludovic
last_name: Righetti
tagline: robotics research results, publications, videos and general activities of the lab
description: >- # this means to ignore newlines until "baseurl:"
  This is the website of the machines in motion laboratory, a robotics research laboratory at New York University
  headed by Ludovic Righetti. We conduct fundamental and applied robotics research with a particular focus on
  autonomous dexterous manipulation and legged locomotion.
  The website lists the labs activities, publications, group members and latest news.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with custom theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.machinesinmotion.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: machines_motion
github_username:  machines-in-motion
scholar_userid: LuA1j4oAAAAJ
logo: /assets/img/mim_logo_black.png


# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-email-protect
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include: ['_pages', '_projects']
exclude:
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  projects:
    output: true
    sort_by: project_order
    


scholar:
  style: ieee
  locale: en
  bibliography_template: bib
  sort_by: year
  order: descending